rvm:
  - "1.8.7"
  - "1.9.2"
  - "1.9.3"
  - "2.0.0"
gemfile:
  - gemfiles/rails23.gemfile
  - gemfiles/rails30.gemfile
  - gemfiles/rails31.gemfile
  - gemfiles/rails32.gemfile
  - gemfiles/rails32_pg.gemfile
  - gemfiles/rails32_mysql.gemfile
  - gemfiles/rails40.gemfile
before_install: bundle install
bundler_args:
matrix:
  exclude:
    - rvm: 2.0.0
      gemfile: gemfiles/rails23.gemfile
    - rvm: 1.8.7
      gemfile: gemfiles/rails40.gemfile
    - rvm: 1.9.2
      gemfile: gemfiles/rails40.gemfile
before_script:
  - psql -c 'create database fuzzily_test;' -U postgres
  - mysql -e 'create database fuzzily_test;'
env:
  global:
    - TRAVIS=TRUE
